apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: tekton-allure-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-pipeline-deployer
  namespace: tekton-allure-demo
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["build.openshift.io"]
    resources: ["buildconfigs", "buildconfigs/instantiatebinary", "builds", "builds/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-pipeline-deployer
  namespace: tekton-allure-demo
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-allure-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-pipeline-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-image-pusher
  namespace: tekton-allure-demo
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-allure-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
