apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-results-pvc
  namespace: tekton-allure-demo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure
  namespace: tekton-allure-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allure
  template:
    metadata:
      labels:
        app: allure
    spec:
      containers:
        - name: allure
          image: frankescobar/allure-docker-service:2.38.1
          ports:
            - containerPort: 5050
          env:
            - name: CHECK_RESULTS_EVERY_SECONDS
              value: "5"
            - name: KEEP_HISTORY
              value: "1"
          volumeMounts:
            - name: results
              mountPath: /app/allure-results
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: allure-results-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: allure
  namespace: tekton-allure-demo
spec:
  selector:
    app: allure
  ports:
    - name: http
      port: 5050
      targetPort: 5050
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: allure
  namespace: tekton-allure-demo
spec:
  to:
    kind: Service
    name: allure
  port:
    targetPort: http
